# Generated by Django 3.2.12 on 2022-05-27 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='option',
            fields=[
                ('optionId', models.AutoField(primary_key=True, serialize=False)),
                ('customOption', models.CharField(max_length=100, unique=True, verbose_name='Custom Option')),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('isDefault', models.BooleanField(default=False, verbose_name='Is Default')),
            ],
        ),
    ]
