# Generated by Django 3.2.13 on 2022-06-24 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customerGroup',
            fields=[
                ('customerGroupId', models.AutoField(primary_key=True, serialize=False)),
                ('customerGroupName', models.CharField(max_length=200, verbose_name='name')),
                ('isDefault', models.BooleanField(default=False, verbose_name='Is Default')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updatedAt', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
        ),
    ]
