# Generated by Django 3.2.13 on 2022-06-24 05:25

import Customer.models
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=24, unique=True, verbose_name='City Name')),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('customerId', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('mobileNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True, verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email Id')),
                ('profileImage', models.ImageField(upload_to='images/', verbose_name='Profile Image')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('emailVarificationDate', models.DateTimeField(blank=True, default=None, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('customerGroup', models.ForeignKey(default=Customer.models.default_customerGroup, on_delete=django.db.models.deletion.CASCADE, to='Customer.customergroup')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('stateId', models.AutoField(primary_key=True, serialize=False)),
                ('stateName', models.CharField(max_length=24, unique=True, verbose_name='State Name')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='customerAddress',
            fields=[
                ('customerAddressId', models.AutoField(primary_key=True, serialize=False)),
                ('addressName', models.CharField(max_length=100, verbose_name='Name')),
                ('building', models.CharField(max_length=200, verbose_name='Building / House No.')),
                ('street', models.CharField(max_length=200, verbose_name='Street')),
                ('postalCode', models.IntegerField(verbose_name='Postal Code')),
                ('landMark', models.CharField(max_length=200, verbose_name='Landmark')),
                ('isDefault', models.BooleanField(default=False, verbose_name='Is Default')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.city')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.customer')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Customer.state')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='stateName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Customer.state'),
        ),
    ]
