# Generated by Django 3.2.13 on 2022-06-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_auto_20220624_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='code',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
