# Generated by Django 3.2.13 on 2022-07-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0003_customer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='emailSentOn',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
