# Generated by Django 3.2.13 on 2022-07-07 06:04

import Block.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('blockId', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.CharField(default=None, max_length=100, unique=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='blockTranslation',
            fields=[
                ('blockTranslationId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Block.block')),
                ('language', models.ForeignKey(default=Block.models.get_language, on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
            ],
            options={
                'verbose_name': 'Block Translation',
                'unique_together': {('language', 'block')},
            },
        ),
    ]
