# Generated by Django 3.2.13 on 2022-07-07 04:21

import Page.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('pageId', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(unique=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='pageTranslation',
            fields=[
                ('contentId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('language', models.ForeignKey(default=Page.models.get_language, on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Page.page')),
            ],
            options={
                'verbose_name': 'Page Translation',
                'unique_together': {('language', 'page')},
            },
        ),
    ]
