# Generated by Django 3.2.12 on 2022-05-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
            ],
        ),
    ]
