# Generated by Django 3.2.13 on 2022-07-07 11:03

import Banner.models
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('bannerId', models.AutoField(primary_key=True, serialize=False)),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='bannerGroup',
            fields=[
                ('bannerGroupId', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('sortOrder', models.IntegerField(default=0, verbose_name='Sort Order')),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled')], default='enabled', max_length=10)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='bannerTranslation',
            fields=[
                ('bannerTranslationId', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', tinymce.models.HTMLField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.banner')),
                ('language', models.ForeignKey(default=Banner.models.get_language, on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
            ],
            options={
                'verbose_name': 'Banner Group Translation',
            },
        ),
        migrations.CreateModel(
            name='bannerImage',
            fields=[
                ('bannerImageId', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('url', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.banner')),
                ('bannerGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.bannergroup')),
            ],
        ),
        migrations.CreateModel(
            name='bannerGroupTranslation',
            fields=[
                ('bannerGroupTranslationId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('bannerGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Banner.bannergroup')),
                ('language', models.ForeignKey(default=Banner.models.get_language, on_delete=django.db.models.deletion.CASCADE, to='Language.language')),
            ],
            options={
                'verbose_name': 'Banner Group Translation',
            },
        ),
    ]
